/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScrollDecorationBar {
        /**
          * 所在位置
          * @type {('top' | 'right')}
          * @memberof ScrollDecorationBar
         */
        "position": 'top' | 'right';
        /**
          * 监控滚动条的element节点
          * @type {HTMLDivElement}
          * @memberof ScrollDecorationBar
         */
        "scrollDom": HTMLDivElement;
        /**
          * 滚动条距离开始距离，当为0时隐藏滚动阴影
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "scrollNum": number;
        /**
          * 显示的z-index层级
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "zIndex": number;
    }
}
declare global {
    interface HTMLScrollDecorationBarElement extends Components.ScrollDecorationBar, HTMLStencilElement {
    }
    var HTMLScrollDecorationBarElement: {
        prototype: HTMLScrollDecorationBarElement;
        new (): HTMLScrollDecorationBarElement;
    };
    interface HTMLElementTagNameMap {
        "scroll-decoration-bar": HTMLScrollDecorationBarElement;
    }
}
declare namespace LocalJSX {
    interface ScrollDecorationBar {
        /**
          * 所在位置
          * @type {('top' | 'right')}
          * @memberof ScrollDecorationBar
         */
        "position"?: 'top' | 'right';
        /**
          * 监控滚动条的element节点
          * @type {HTMLDivElement}
          * @memberof ScrollDecorationBar
         */
        "scrollDom"?: HTMLDivElement;
        /**
          * 滚动条距离开始距离，当为0时隐藏滚动阴影
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "scrollNum"?: number;
        /**
          * 显示的z-index层级
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "zIndex"?: number;
    }
    interface IntrinsicElements {
        "scroll-decoration-bar": ScrollDecorationBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scroll-decoration-bar": LocalJSX.ScrollDecorationBar & JSXBase.HTMLAttributes<HTMLScrollDecorationBarElement>;
        }
    }
}
