/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScrollShadowBar {
    }
}
declare global {
    interface HTMLScrollShadowBarElement extends Components.ScrollShadowBar, HTMLStencilElement {
    }
    var HTMLScrollShadowBarElement: {
        prototype: HTMLScrollShadowBarElement;
        new (): HTMLScrollShadowBarElement;
    };
    interface HTMLElementTagNameMap {
        "scroll-shadow-bar": HTMLScrollShadowBarElement;
    }
}
declare namespace LocalJSX {
    interface ScrollShadowBar {
    }
    interface IntrinsicElements {
        "scroll-shadow-bar": ScrollShadowBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scroll-shadow-bar": LocalJSX.ScrollShadowBar & JSXBase.HTMLAttributes<HTMLScrollShadowBarElement>;
        }
    }
}
