/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QxContextMenu {
        /**
          * 是否悬浮
          * @return {Promise<boolean>}
          * @memberof QxContextMenu
         */
        "isHover": () => Promise<boolean>;
        /**
          * 菜单数据
          * @type {any[]}
          * @memberof QxContextMenu
         */
        "menus": any[];
        /**
          * 显示菜单
          * @param e
          * @return {Promise<void>}
          * @memberof QxContextMenu
         */
        "show": (e: MouseEvent) => Promise<void>;
    }
    interface QxMain {
    }
    interface ScrollDecorationBar {
        /**
          * 所在位置
          * @type {('top' | 'right')}
          * @memberof ScrollDecorationBar
         */
        "position": 'top' | 'right';
        /**
          * 监控滚动条的element节点
          * @type {HTMLDivElement}
          * @memberof ScrollDecorationBar
         */
        "scrollDom": HTMLDivElement;
        /**
          * 滚动条距离开始距离，当为0时隐藏滚动阴影
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "scrollNum": number;
        /**
          * 显示的z-index层级
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "zIndex": number;
    }
}
declare global {
    interface HTMLQxContextMenuElement extends Components.QxContextMenu, HTMLStencilElement {
    }
    var HTMLQxContextMenuElement: {
        prototype: HTMLQxContextMenuElement;
        new (): HTMLQxContextMenuElement;
    };
    interface HTMLQxMainElement extends Components.QxMain, HTMLStencilElement {
    }
    var HTMLQxMainElement: {
        prototype: HTMLQxMainElement;
        new (): HTMLQxMainElement;
    };
    interface HTMLScrollDecorationBarElement extends Components.ScrollDecorationBar, HTMLStencilElement {
    }
    var HTMLScrollDecorationBarElement: {
        prototype: HTMLScrollDecorationBarElement;
        new (): HTMLScrollDecorationBarElement;
    };
    interface HTMLElementTagNameMap {
        "qx-context-menu": HTMLQxContextMenuElement;
        "qx-main": HTMLQxMainElement;
        "scroll-decoration-bar": HTMLScrollDecorationBarElement;
    }
}
declare namespace LocalJSX {
    interface QxContextMenu {
        /**
          * 菜单数据
          * @type {any[]}
          * @memberof QxContextMenu
         */
        "menus"?: any[];
    }
    interface QxMain {
    }
    interface ScrollDecorationBar {
        /**
          * 所在位置
          * @type {('top' | 'right')}
          * @memberof ScrollDecorationBar
         */
        "position"?: 'top' | 'right';
        /**
          * 监控滚动条的element节点
          * @type {HTMLDivElement}
          * @memberof ScrollDecorationBar
         */
        "scrollDom"?: HTMLDivElement;
        /**
          * 滚动条距离开始距离，当为0时隐藏滚动阴影
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "scrollNum"?: number;
        /**
          * 显示的z-index层级
          * @type {number}
          * @memberof ScrollDecorationBar
         */
        "zIndex"?: number;
    }
    interface IntrinsicElements {
        "qx-context-menu": QxContextMenu;
        "qx-main": QxMain;
        "scroll-decoration-bar": ScrollDecorationBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qx-context-menu": LocalJSX.QxContextMenu & JSXBase.HTMLAttributes<HTMLQxContextMenuElement>;
            "qx-main": LocalJSX.QxMain & JSXBase.HTMLAttributes<HTMLQxMainElement>;
            "scroll-decoration-bar": LocalJSX.ScrollDecorationBar & JSXBase.HTMLAttributes<HTMLScrollDecorationBarElement>;
        }
    }
}
